### ISSUE TITLE
No leave menu entry at all

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#462]
With system language in italian no leave menu entry is provided because  in lxqt-session-git/src/lxqt-session/lxqtleave/ they are no generic .desktop files, only *_pt. and *.de.desktop are present.

Creating generic desktop or adding _it.desktop files  solves.

**Comment by pmattern** [comment]
Running up-to-date Arch Linux x86_64 with recent Git versions of all LXQt components I can't confirm your findings, see screenshot, taken from a session launched with locale set to it_IT.UTF-8.

Topic "Leave" in Application menu's top level is provided by /usr/share/desktop-directories/lxqt-leave.directory which belongs to lxqt-common (for now, will probably be moved to lxmenu-data some day), topics "Lock Screen" and "Hibernate" ... "Suspend" by /usr/share/applications/lxqt-\<action\>.desktop which belong to lxqt-session.
So changes in lxqt-session actually can't influence "Leave".

Probably there were some artifacts due to the lots of changes that took place in recent days and you'll see the same as in the screenshot if you recompile recent Git versions of all components.

Side-note regarding translations: Those of topic "Leave" are done in lxqt-common - menu - translations. Also, I was wondering whether it's intentional that you created file lxqt-hibernate_it.desktop but didn't include it in your PRs.

![lxqt applications menu italian aus vm](https://cloud.githubusercontent.com/assets/9860801/5990225/1a4c50b2-a9a7-11e4-8f7f-219b451d7fb3.png)

**Comment by stefonarch** [comment]
I know only what happened: updating all git-AUR packages resulted in no
leave menu, creating the .desktop files in /usr/share/applications
resolved; there were none, if there is even only one leave menu appears
with one voice on my system. First I looked at and it was okay.

$cat /usr/share/desktop-directories/lxqt-leave.directory
[Desktop Entry]
Name=Leave
Comment=Leave Session
Icon=system-shutdown
Type=Directory


Comment[de]=Sitzung verlassen
Name[de]=Verlassen
Name[it]=Esci
Comment[it]=Termina sessione

I can recreate  the error by removing the 5 desktop files again.

I've waited to create pull-request for hibernate.desktop because it did
not work for me with lxqt-leave --hibernate, wanted to test why.

Il 01/02/2015 00:18, Peter Mattern ha scritto:
> Running up-to-date Arch Linux x86_64 with recent Git versions of all
> LXQt components I can't confirm your findings, see screenshot, taken
> from a session launched with locale set to it_IT.UTF-8.
> 
> Topic "Leave" in Application menu's top level is provided by
> /usr/share/desktop-directories/lxqt-leave.directory which belongs to
> lxqt-common (for now, will probably be moved to lxmenu-data some day),
> topics "Lock Screen" and "Hibernate" ... "Suspend" by
> /usr/share/applications/lxqt-<action>.desktop which belong to lxqt-session.
> So changes in lxqt-session actually can't influence "Leave".
> 
> Probably there were some artifacts due to the lots of changes that took
> place in recent days and you'll see the same as in the screenshot if you
> recompile recent Git versions of all components.
> 
> Side-note regarding translations: Those of topic "Leave" are done in
> lxqt-common - menu - translations. Also, I was wondering whether it's
> intentional that you created file lxqt-hibernate_it.desktop but didn't
> include it in your PRs.
> 
> lxqt applications menu italian aus vm
> <https://cloud.githubusercontent.com/assets/9860801/5990225/1a4c50b2-a9a7-11e4-8f7f-219b451d7fb3.png>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/462#issuecomment-72342134>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************

**Comment by pmattern** [comment]
LXQt Application menu is built automatically. If no \*.desktop file intended to be shown in a certain top-level item is available, the item won't be shown. E. g. if no games are installed, item "Games" will be missing. If /usr/share/applications/lxqt-{hibernate,lockscreen,logout,reboot,shutdown,suspend}.desktop are missing, item "Leave" isn't shown. This is expected behaviour and *not specific to Italian*.
Still I think you ran into something similar as described in https://github.com/lxde/lxqt/issues/437#issuecomment-71393203. During transition those files lxqt-\<action\>.desktop didn't work for a while last week hence no item "Leave". But this is fixed. So again, if you recompile latest Git version your problem should have gone.

**Comment by stefonarch** [comment]
I've recompiled   2 days ago.
I tested this again on a second machine with arch 32bit which has no
lxqt at all installed yet and in effect, they get created regularly.
112mb Ram after login :)

Hibernate works here but creates reboot...

So sorry, remain just the italian translations.

Il 01/02/2015 11:35, Peter Mattern ha scritto:
> LXQt Application menu is built automatically. If no *.desktop file
> intended to be shown in a certain top-level item is available, the item
> won't be shown. E. g. if no games are installed, item "Games" will be
> missing. If
> /usr/share/applications/lxqt-{hibernate,lockscreen,logout,reboot,shutdown,suspend}.desktop
> are missing, item "Leave" isn't shown. This is expected behaviour and
> /not specific to Italian/.
> Still I think you ran into something similar as described in #437
> (comment)
> <https://github.com/lxde/lxqt/issues/437#issuecomment-71393203>. During
> transition those files lxqt-<action>.desktop didn't work for a while
> last week hence no item "Leave". But this is fixed. So again, if you
> recompile latest Git version your problem should have gone.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/462#issuecomment-72359596>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************

**Comment by paulolieuthier** [comment]
@stefonarch I don't understand. Can you still reproduce this bug?

**Comment by stefonarch** [comment]
No, it was connected to some other things, on a clean machine it was not
to repruce,  all ok with desktop files for leave menu present in
/usr/share/applications.
Sorry for the noise.

Il 04/02/2015 11:58, Paulo Lieuthier ha scritto:
> @stefonarch <https://github.com/stefonarch> I don't understand. Can you
> still reproduce this bug?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/462#issuecomment-72836122>.
> 

-- 
********************************
Stef Binde
via della pieve 2
I-56024 Corazzano PI

Tel: ++39 0571 17 30 104
PGP: 0x728D9707

stef.binde@riseup.net
*******************************

**Comment by paulolieuthier** [comment]
No problem. Thanks for your contributions!
