### ISSUE TITLE
Add different widgets seems adding always the same widget 

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#927]
Some time now I see this behaviour, now I tested on a clean user, latest arch AUR packages:
Adding keyboard indicator and  several sensors all reproduce the same icon  (I guess the one from the last widget added, I saw also once a lot of keyboard indicators multiplied), until killing and restarting panel (or logout/login).

Sometimes the new icons seem overlapping  with other elements.
 
![fjnhaxx](https://cloud.githubusercontent.com/assets/10681413/12057384/d3a8a296-af40-11e5-9ae0-fea0d99d1a49.png)

**Comment by paulolieuthier** [comment]
The plugin is added correctly (as @stefonarch said, restarting the panel confirms that), the problem is "visual". After adding a plugin, a lot of XCB errors are printed:

```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 4786, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 4837, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 4893, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 4894, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 4895, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 5125, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 5135, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 5221, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 5304, resource id: 25165893, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 5399, resource id: 25165893, major code: 130 (Unknown), minor code: 3
```

**Comment by paulolieuthier** [comment]
@stefonarch what version of Qt do you have installed? There was recent Qt updates in Arch.

**Comment by stefonarch** [comment]
Everything was up-to-date when I tested, qtplugininfo-qt5 --v says  qplugininfo 5.5.1 
I had this visual  error for some weeks, but thougt it depends on something in my home, laso because I saw no other bugs filed about that.

**Comment by paulolieuthier** [comment]
@palinek what version of Qt do you have installed? Can you reproduce it?

**Comment by palinek** [comment]
> @palinek what version of Qt do you have installed? Can you reproduce it?

No, I don't see such behaviour here.
```
Qt 5.5.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20151219) on "xcb"
OS: Debian GNU/Linux stretch/sid [linux version 4.3.0-1-amd64]
```

**Comment by paulolieuthier** [comment]
I think it's a problem with Arch packaging. Here it's version 5.5.1-7. [Here](https://projects.archlinux.org/svntogit/packages.git/log/trunk?h=packages/qt5) is the git log for qt5-base's PKGBUILD.

**Comment by pmattern** [comment]
Cannot reproduce the problem on an up to date Arch system either. I guess it's due to not recompiling LXQt against *the latest Arch packages* of Qt.

@stefonarch
Something like this
```
$ qtplugininfo-qt5 --v 
qplugininfo 5.5.1
```
isn't too meaningful as Arch Linux made several (Arch Linux) releases of Qt 5.5.1, see the link posted by @paulolieuthier above.
I'd suggest you recompile *all* LXQt components once more on an up to date system and see what's happening. Maybe you could even test on a new user profile then.

**Comment by stefonarch** [comment]
Done, no change same behaviour, on  a clean user or on  my user.
2015-12-31 18:04] reinstalled liblxqt-git (0.10.0.11.gd5cd5a2-1)
[2015-12-31 18:05] reinstalled libqtxdg-git (1.3.0.2.g58a6373-1)
[2015-12-31 18:06] upgraded lxqt-common-git (0.10.0.4.g8773fb3-1 -> 0.10.0.6.g24a0a52-1)
[2015-12-31 18:07] reinstalled lxqt-runner-git (0.10.0.6.gb498258-1)
[2015-12-31 18:08] upgraded libfm-qt-git (r304.fa6f637-1 -> r307.9a598f1-1)
[2015-12-31 18:09] upgraded lxqt-config-git (0.10.0.12.gb6d171d-1 -> 0.10.0.18.g0a8b9b4-1)
[2015-12-31 18:11] reinstalled pcmanfm-qt-git (0.10.1.6.gfb467e1-1)
[2015-12-31 18:11] reinstalled lxqt-policykit-git (0.10.0.3.g6058410-1)
[2015-12-31 18:12] reinstalled libsysstat-git (0.3.1.1.gcef43c0-1)
[2015-12-31 18:12] reinstalled lxqt-notificationd-git (0.10.0.6.g56d4b83-1)
[2015-12-31 18:13] reinstalled lxqt-appswitcher-git (r7.a59993d-1)
[2015-12-31 18:13] reinstalled lxqt-sudo-git (0.10.0.3.ga68d11a-1)
[2015-12-31 18:14] reinstalled lxqt-session-git (0.10.0.12.gf63c55e-1)
[2015-12-31 18:18] reinstalled lxqt-globalkeys-git (0.10.0.7.gbdb2b0b-1)
[2015-12-31 18:19] reinstalled lxqt-powermanagement-git (0.10.0.6.g5050da6-1)
[2015-12-31 18:20] reinstalled lxqt-qtplugin-git (0.10.0-1)
[2015-12-31 19:06] installed lxqt-panel-git (0.10.0.35.g9d6345e-1)


Looking for eventually conflicting files from older compiling I found only some empty folders and files /usr/local/include/lxqt
/usr/local/lib64/liblxqtwallet.so
/usr/local/lib64/lxqt-panel[/code]
/usr/local/share/qCheckGMail/lxqt_wallet
/usr/local/share/qCheckGMail/lxqt_wallet/translations.qm

**Comment by palinek** [comment]
@stefonarch are you still observing this issue ?

**Comment by stefonarch** [comment]
Yes, I forgot about it, but I've just tested, it's still the same,. 
I recompiled all stuff some days ago, panel today.
Will  test it later on a clean user.

**Comment by paulolieuthier** [comment]
I don't reproduce it anymore. Qt 5.6.0-2 and KWindowSystem 5.20.0-1 on Arch.

**Comment by stefonarch** [comment]
Just tested on my account with same qt version &arch but it's still the same, have to test it on a clean user.

**Comment by paulolieuthier** [comment]
Well, short after not seeing it anymore, I got back reproducing it again. I've tried hacking a bit, not success. I read it may be related to driver issues and compositing. @palinek, @pmattern, @stefonarch: what video drivers are you using? And WM?

**Comment by stefonarch** [comment]
I always had this bug, I just do not see it because I never change widgets anymore, have found my percect layout.
Video is Intel Haswell-ULT Integrated Graphics Controller, WM is openbox+compton,   kwin_x11 was always  unusable here.

**Comment by palinek** [comment]
I'm on intel, openbox, no compositor.

**Comment by pmattern** [comment]
Meanwhile I stumbled upon this problem as well while debugging a panel crash due to plugin-mount, see https://github.com/lxde/lxqt/issues/1013#issuecomment-209591553 ("When plugin-quicklaunch hosting ...").
Interestingly I was seeing the very same error message `QXcbConnection: [...]` that @paulolieuthier posted [above](https://github.com/lxde/lxqt/issues/927#issuecomment-168079184) and the commit fixing the crash addressed in #1013 made this message disappear and the correct icons were used as well.
So maybe there's some correlation between the said error message and the faulty icons?

The findings were made in an Arch Linux guest in a KVM/QEMU virtual machine featuring the virtual QXL graphics hardware and using latest VCS checkout of xf86-video-qxl.

**Comment by paulolieuthier** [comment]
> So maybe there's some correlation between the said error message and the faulty icons?

Well, maybe, but new plugins are still not displayed correctly to me.

**Comment by pmattern** [comment]
>>  So maybe there's some correlation between the said error message and the faulty icons?
> Well, maybe, but new plugins are still not displayed correctly to me.

Do you see the said error messages on the shell of a terminal emulator the panel was launched from upon adding the plugins in question?

**Comment by paulolieuthier** [comment]
Yes.

**Comment by stefonarch** [comment]
Just noticed that on Ubuntu 16.04 and 14.04 (in VM) with   builds from https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily this bug is not present...

**Comment by stefonarch** [comment]
Just noticed that on Ubuntu 16.04 and 14.04 (in VM) with builds from https://launchpad.net/~lubuntu-dev/+archive/ubuntu/lubuntu-daily this bug is not present...

**Comment by stefonarch** [comment]
Update: The above is not completely true.
 I noticed that it was like that with the default panel, but adding a second clean panel 
a) adding clock crashs panel 
b) adding other widgets they do not get displayed until restart panel 
c) same bug: adding a widget the last added icon gets doubled.

**Comment by luis-pereira** [comment]
@stefonarch Is this still valid ? With Qt 5.7 it vanished to me.

**Comment by stefonarch** [comment]
Just tested it on a clean user -yes, it's still there, also on my user, up-to date arch.

**Comment by luis-pereira** [comment]
Which Qt version are you using ?

**Comment by paulolieuthier** [comment]
I can still reproduce it as well. Qt 5.7. Will gather more details later today.

**Comment by stefonarch** [comment]
pacman -Qi qt5-base 
Nome                      : qt5-base
Versione                  : 5.7.0-1

**Comment by paulolieuthier** [comment]
```shell
$ pacman -Qii qt5-base | grep Version 
Version         : 5.7.0-2
```

When I run lxqt-panel and try to add another widget, I get:

```
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6405, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6410, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6415, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6420, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6425, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6430, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6435, resource id: 29360181, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 8 (BadMatch), sequence: 6440, resource id: 29360181, major code: 130 (Unknown), minor code: 3
...
```

One detail I hadn't noticed: the list of XCB errors is infinete. All `BadMatch`, same id, but differente "sequence" number.

**Comment by stefonarch** [comment]
Same here, but my sequence numbers more "different", yours are just in step of 5
`QXcbConnection: XCB error: 8 (BadMatch), sequence: 12119, resource id: 67108953, major code: 130 (Unknown), minor code: 3
  sequence: 12147 
 sequence: 12389 
  sequence: 12405
 sequence: 15560`

**Comment by tsujan** [comment]
I don't see this problem (with Openbox or Compiz) and have these graphics cards:

On laptop (Debian):
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

On desktop computer (Manjaro):
01:00.0 VGA compatible controller: NVIDIA Corporation G96 [GeForce 9500 GT] (rev a1)

**Comment by stefonarch** [comment]
I notice that three lines are generated when adding a widget, and every mouseover or mouse away or onclick creates a new line. 
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller

**Comment by luis-pereira** [comment]
I tried and tried. I can't reproduce it anymore.

**Comment by paulolieuthier** [comment]
I'd like to say it as well, but If I and @stefonarch are still reproducing it, it means users will as well, and adding widgets is a very basic feature.

**Comment by luis-pereira** [comment]
@paulolieuthier Sure @paulolieuthier. My point was that I can't help with it.

**Comment by paulolieuthier** [comment]
Yeah, I got you. I was just expressing my frustration with this bug.

**Comment by palinek** [comment]
Finaly I've got this reproduced in QEMU with [manjaro image 2016.03](https://sourceforge.net/projects/manjarolinux/files/community/LXQT/2016.03/) and updated lxqt-components to recent git checkouts.

After many 'try and fail' attempts I've realized that this "strange" behaviour happens only if the panels sets the `Qt::WA_TranslucentBackground` attribute. If commented out:
```diff
diff --git a/panel/lxqtpanel.cpp b/panel/lxqtpanel.cpp
index c5d0660..35f2dc0 100644
--- a/panel/lxqtpanel.cpp
+++ b/panel/lxqtpanel.cpp
@@ -161,7 +161,7 @@ LXQtPanel::LXQtPanel(const QString &configGroup, LXQt::Settings *settings, QWidg
     //Enables tooltips for inactive windows.
     setAttribute(Qt::WA_AlwaysShowToolTips);
     //Indicates that the widget should have a translucent background, i.e., any non-opaque regions of the widgets will be translucent because the widget will have an alpha channel. Setting this ...
-    setAttribute(Qt::WA_TranslucentBackground);
+    //setAttribute(Qt::WA_TranslucentBackground);
     //Allows data from drag and drop operations to be dropped onto the widget (see QWidget::setAcceptDrops()).
     setAttribute(Qt::WA_AcceptDrops);
```
the wrong rendering doesn't happen. But right now I have no clue how to avoid this.

**Comment by technic** [comment]
There is an issue with icons. Left 'show desktop' is added and as a result has bad outlook.

![image](https://cloud.githubusercontent.com/assets/1092613/18065557/a34d3f36-6e34-11e6-9655-0c54e9a728b1.png)

**Comment by technic** [comment]
Well, after moving widget icon becomes normal.

**Comment by technic** [comment]
git bisect shows issue in commit https://github.com/lxde/lxqt-panel/commit/2d161d2c049f351bd84aabaca72ae7207c242160

tested with recent Arch Linux (qt 5.7.0)

**Comment by paulolieuthier** [comment]
@technic thanks for your help!! This may be really helpful, although I still have no idea how to fix the bug.

**Comment by palinek** [comment]
@technic Great! Many thanks... now I've finaly fixed the issue. 

@stefonarch Please, confirm, that it's fixed now (with the lxde/lxqt-panel@986bb2a and lxde/lxqt-common@de7e439).

**Comment by technic** [comment]
It works!

**Comment by technic** [comment]
Oh, Application Menu search field background is broken. Suppose that it is related.

**Comment by palinek** [comment]
> Oh, Application Menu search field background is broken. Suppose that it is related.

I believe, that this isn't related (the menu is a separate top level widget/window) and it is already reported/discussed in #1109

**Comment by stefonarch** [comment]
Works perfect.
After 8 months it's good to see the fix, thanks to all!

**Comment by paulolieuthier** [comment]
#1109 happens only after updating/reinstalling the used theme. @technic is the menu search field still broken on a fresh session?

**Comment by paulolieuthier** [comment]
BTW, @palinek I'm your fan! @technic thanks again!
